# Generated by Django 4.0.3 on 2022-04-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
