# Generated by Django 4.0.3 on 2022-04-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_rename_employee_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
