# Generated by Django 4.0.3 on 2022-04-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_app.customers')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basic_app.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Orders_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prod_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('units_remain', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('order_id', models.ManyToManyField(through='basic_app.Orders_Products', to='basic_app.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders_products',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.products'),
        ),
    ]
