# Generated by Django 4.0.3 on 2022-04-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_orders_orders_products_products_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='employees',
            table='employees',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orders_products',
            table='orders_products',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
